### ISSUE TITLE
My Pricing Page Looks Rough

### ISSUE THREAD

**Issue by JohnOHFS** [andrewculver/koudoku#150]
So I've added the @import "koudoku/pricing-table" line in the applications.scss file and my pricing page still looks rough. I've also got bootstrap and bootstrap-sprockets imported.  Doesn't look anything like the sample site though.  Any suggestions?  Here's a link to the development site so you can see what it looks like: https://videocourse.herokuapp.com/pricing 

Thanks!

**Comment by blake41** [comment]
Just did a basic install and my page looks exactly the same.  Not sure what's up but the server is telling me [2016-03-10 16:45:52] ERROR bad URI `W/"58c120543fdc6ae8a3de3a5bee885a97"'.


Started GET "/assets/application.self-d885a0a66bd595c10edb24f8879f94e334d88be0730c4d7c7a7b57c731c09037.css?body=1" for ::1 at 2016-03-10 16:45:52 -0500
[2016-03-10 16:45:52] ERROR bad Request-Line `'.


Started GET "/assets/koudoku/pricing-table.self-ddc810e2abb2a663f954387946eb76cbe77382437cee2a9d6fd2d9d66154374b.css?body=1" for ::1 at 2016-03-10 16:45:52 -0500

[2016-03-10 16:45:52] ERROR bad Request-Line `'.

Started GET "/assets/jquery.self-660adc51e0224b731d29f575a6f1ec167ba08ad06ed5deca4f1e8654c135bf4c.js?body=1" for ::1 at 2016-03-10 16:45:52 -0500
[2016-03-10 16:45:52] ERROR bad Request-Line `'.


Started GET "/assets/jquery_ujs.self-e87806d0cf4489aeb1bb7288016024e8de67fd18db693fe026fe3907581e53cd.js?body=1" for ::1 at 2016-03-10 16:45:52 -0500
[2016-03-10 16:45:52] ERROR bad Request-Line `'.


Started GET "/assets/turbolinks.self-c37727e9bd6b2735da5c311aa83fead54ed0be6cc8bd9a65309e9c5abe2cbfff.js?body=1" for ::1 at 2016-03-10 16:45:52 -0500

[2016-03-10 16:45:52] ERROR bad Request-Line `'.

Started GET "/assets/application.self-3b8dabdc891efe46b9a144b400ad69e37d7e5876bdc39dee783419a69d7ca819.js?body=1" for ::1 at 2016-03-10 16:45:52 -0500
[2016-03-10 16:45:52] ERROR bad Request-Line `'.
[2016-03-10 16:45:52] ERROR bad Request-Line `If-Modified-Since: Thu, 10 Mar 2016 21:31:26 GMT'.

**Comment by blake41** [comment]
@JohnOHFS I fixed mine.  For some reason all the bootstrap css was not getting loaded.  I was using the twitter bootstrap rails gem and i'm not sure why that wasn't loading all of the bootstrap stuff and only some of it.  I did a manual install of bootstrap css and everything looks good now

**Comment by JohnOHFS** [comment]
@blake41 How did you load it manually?

**Comment by JohnOHFS** [comment]
It's an issue with how the css is loaded.  I just opted for a different custom pricing page.

**Comment by Ray-Sutton** [comment]
@blake41 Any help with getting the plans page to look better and load correctly?

**Comment by blake41** [comment]
@Ray-Sutton i did this a long time ago so don't remember exactly, but i think what i was saying was that rather than using the gem, download the bootstrap css files into your vendor/css directory use the application css file to require the bootstrap files and load the bootrap files "manually" that way

**Comment by Ray-Sutton** [comment]
@blake41 Got it, thank you. I'll try it a bit later but I know exactly what needs to be done. Thanks!

**Comment by JohnOHFS** [comment]
@Ray-Sutton I ended up just touching up the css and adding bootstrap elements to correct the look.
